services:
  backend:
    build: backend
    container_name: "moba-backend"
    ports:
      - "8080:8080"
    networks:
      - tts
      - backend

  frontend:
    build: frontend
    container_name: "moba-frontend"
    ports:
      - "80:3000"
      #- "443:443"
    networks:
      - backend

  tts:
    build: tts
    container_name: "moba-tts"
    ports:
      - "8000:80"
    networks:
      - tts
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [ gpu ]

networks:
  tts:
    name: tts_network
    driver: bridge
  backend:
    name: backend_network
    driver: bridge