spring.application.name=modellbahn
spring.jpa.hibernate.ddl-auto = none

spring.datasource.url = jdbc:sqlite:moba.sqlite
spring.datasource.driver-class-name = org.sqlite.JDBC

spring.flyway.enabled=true
spring.flyway.locations=classpath:migrations/{vendor}

spring.datasource.username = admin
spring.datasource.password = admin